
IF OBJECT_ID('MRCONSO') IS NOT NULL DROP TABLE MRCONSO

CREATE TABLE MRCONSO
(
    CUI NCHAR(8) NOT NULL,
    LAT NCHAR(3) NOT NULL,
    TS NCHAR(1) NOT NULL,
    LUI NCHAR(10) NOT NULL,
    STT NCHAR(3) NOT NULL,
    SUI NCHAR(10) NOT NULL,
    ISPREF NCHAR(1) NOT NULL,
    AUI NCHAR(9) NOT NULL,
    SAUI NVARCHAR(50) NULL,
    SCUI NVARCHAR(100) NULL,
    SDUI NVARCHAR(100) NULL,
    SAB NVARCHAR(20) NOT NULL,
    TTY NVARCHAR(20) NOT NULL,
    CODE NVARCHAR(100) NOT NULL,
    STR NVARCHAR(3000) NOT NULL,
    SRL INT NOT NULL,
    SUPPRESS NCHAR(1) NOT NULL,
    CVF INT
)

IF OBJECT_ID('MRSAT') IS NOT NULL DROP TABLE MRSAT
CREATE TABLE MRSAT
(
    CUI NCHAR(8) NOT NULL,
    LUI NCHAR(10) NULL,
    SUI NCHAR(10) NULL,
    METAUI NVARCHAR(100) NULL,
    STYPE NVARCHAR(50) NOT NULL,
    CODE NVARCHAR(100) NULL,
    ATUI NCHAR(11) NOT NULL,
    SATUI NVARCHAR(50) NULL,
    ATN NVARCHAR(100) NOT NULL,
    SAB NVARCHAR(20) NOT NULL,
    ATV NVARCHAR(MAX) NULL,
    SUPPRESS NCHAR(1) NOT NULL,
    CVF INT NULL
)

IF OBJECT_ID('MRREL') IS NOT NULL DROP TABLE MRREL
CREATE TABLE [dbo].[MRREL] (
	[CUI1] NCHAR(8) NOT NULL,
	[AUI1] NVARCHAR(9) NULL,
	[STYPE1] NVARCHAR(50) NOT NULL,
	[REL] NCHAR(4) NOT NULL,
	[CUI2] NCHAR(8) NOT NULL,
	[AUI2] NVARCHAR(9) NULL,
	[STYPE2] NVARCHAR(50) NOT NULL,
	[RELA] NVARCHAR(100) NULL,
	[RUI] NVARCHAR(10) NOT NULL,
	[SRUI] NVARCHAR(50) NULL,
	[SAB] NVARCHAR(20) NOT NULL,
	[SL] NVARCHAR(20) NOT NULL,
	[RG] NVARCHAR(10) NULL,
	[DIR] NCHAR(1) NULL,
	[SUPPRESS] NCHAR(1) NOT NULL,
	[CVF] INT NULL
);

IF OBJECT_ID('MRHIER') IS NOT NULL DROP TABLE MRHIER
CREATE TABLE [dbo].[MRHIER](
	[CUI] NCHAR(8) NOT NULL,
	[AUI] NVARCHAR(9) NOT NULL,
	[CXN] INT NOT NULL,
	[PAUI] NVARCHAR(10) NULL,
	[SAB] NVARCHAR(40) NOT NULL,
	[RELA] NVARCHAR(100) NULL,
	[PTR] NVARCHAR(1000) NULL,
	[HCD] NVARCHAR(100) NULL,
	[CVF] INT NULL
);

IF OBJECT_ID('MRSTY') IS NOT NULL DROP TABLE MRSTY
CREATE TABLE [dbo].[MRSTY](
	[CUI] NCHAR(8) NOT NULL,
	[TUI] NCHAR(4) NOT NULL,
	[STN] NVARCHAR(100) NOT NULL,
	[STY] NVARCHAR(50) NOT NULL,
	[ATUI] NVARCHAR(11) NOT NULL,
	[CVF] INT NULL
);

IF OBJECT_ID('MRMAP') IS NOT NULL DROP TABLE MRMAP
CREATE TABLE [dbo].[MRMAP](
	[MAPSETCUI] NCHAR(8) NOT NULL,
	[MAPSETSAB] NVARCHAR(40) NOT NULL,
	[MAPSUBSETID] NVARCHAR(10) NULL,
	[MAPRANK] INT NULL,
	[MAPID] NVARCHAR(50) NOT NULL,
	[MAPSID] NVARCHAR(50) NULL,
	[FROMID] NVARCHAR(50) NOT NULL,
	[FROMSID] NVARCHAR(50) NULL,
	[FROMEXPR] NVARCHAR(4000) NOT NULL,
	[FROMTYPE] NVARCHAR(50) NOT NULL,
	[FROMRULE] NVARCHAR(4000) NULL,
	[FROMRES] NVARCHAR(4000) NULL,
	[REL] NVARCHAR(4) NOT NULL,
	[RELA] NVARCHAR(100) NULL,
	[TOID] NVARCHAR(50) NULL,
	[TOSID] NVARCHAR(50) NULL,
	[TOEXPR] NVARCHAR(4000) NULL,
	[TOTYPE] NVARCHAR(50) NULL,
	[TORULE] NVARCHAR(4000) NULL,
	[TORES] NVARCHAR(4000) NULL,
	[MAPRULE] NVARCHAR(4000) NULL,
	[MAPRES] NVARCHAR(4000) NULL,
	[MAPTYPE] NVARCHAR(50) NULL,
	[MAPATN] NVARCHAR(100) NULL,
	[MAPATV] NVARCHAR(4000) NULL,
	[CVF] INT NULL
);

IF OBJECT_ID('MRDEF') IS NOT NULL DROP TABLE MRDEF
CREATE TABLE [dbo].[MRDEF](
	[CUI] NCHAR(8) NOT NULL,
	[AUI] NCHAR(9) NULL,
	[ATUI] NVARCHAR(11) NOT NULL,
    [SATUI] NVARCHAR(50) NULL,
    [SAB] NVARCHAR(20) NOT NULL,
	[DEF] NVARCHAR(MAX) NOT NULL,
    [SUPPRESS] NCHAR(1) NOT NULL,
	[CVF] INT NULL
);

IF OBJECT_ID('MRCUI') IS NOT NULL DROP TABLE MRCUI
CREATE TABLE [dbo].[MRCUI](
	[CUI1] NCHAR(8) NOT NULL,
	[VER] NCHAR(10) NULL,
	[REL] NCHAR(4) NULL,
    [RELA] NVARCHAR(100) NULL,
    [MAPREASON] NVARCHAR(4000) NULL,
	[CUI2] NCHAR(8) NULL,
    [MAPIN] NCHAR(1) NULL,
    [CVF] INT NULL
);

IF OBJECT_ID('MRXNS_ENG') IS NOT NULL DROP TABLE MRXNS_ENG
CREATE TABLE MRXNS_ENG (
    LAT	NCHAR(3) NOT NULL,
    NSTR NVARCHAR(3000) NOT NULL,
    CUI	NCHAR(8) NOT NULL,
    LUI	NVARCHAR(10) NOT NULL,
    SUI	NVARCHAR(10) NOT NULL
);

IF OBJECT_ID('MRXNW_ENG') IS NOT NULL DROP TABLE MRXNW_ENG
CREATE TABLE MRXNW_ENG (
    LAT	NCHAR(3) NOT NULL,
    NWD	NVARCHAR(100) NOT NULL,
    CUI	NCHAR(8) NOT NULL,
    LUI	NVARCHAR(10) NOT NULL,
    SUI	NVARCHAR(10) NOT NULL
)

IF OBJECT_ID('MRXW_ENG') IS NOT NULL DROP TABLE MRXW_ENG
CREATE TABLE MRXW_ENG (
    LAT	NCHAR(3) NOT NULL,
    WD	NVARCHAR(200) NOT NULL,
    CUI	NCHAR(8) NOT NULL,
    LUI	NVARCHAR(10) NOT NULL,
    SUI	NVARCHAR(10) NOT NULL
)

IF OBJECT_ID('MRSMAP') IS NOT NULL DROP TABLE MRSMAP
CREATE TABLE MRSMAP (
    MAPSETCUI	NCHAR(8) NOT NULL,
    MAPSETSAB	NVARCHAR(40) NOT NULL,
    MAPID	    NVARCHAR(50) NOT NULL,
    MAPSID	    NVARCHAR(50),
    FROMEXPR	NVARCHAR(4000) NOT NULL,
    FROMTYPE	NVARCHAR(50) NOT NULL,
    REL	        NVARCHAR(4) NOT NULL,
    RELA	    NVARCHAR(100),
    TOEXPR	    NVARCHAR(4000),
    TOTYPE	    NVARCHAR(50),
    CVF	        INT
);

IF OBJECT_ID('MRAUI') IS NOT NULL DROP TABLE MRAUI
CREATE TABLE MRAUI (
    AUI1	NVARCHAR(9) NOT NULL,
    CUI1	NCHAR(8) NOT NULL,
    VER	    NVARCHAR(10) NOT NULL,
    REL	    NVARCHAR(4),
    RELA	NVARCHAR(100),
    MAPREASON	NVARCHAR(4000) NOT NULL,
    AUI2	NVARCHAR(9) NOT NULL,
    CUI2	NCHAR(8) NOT NULL,
    MAPIN	NCHAR(1) NOT NULL,
    CVF	        INT
);

IF OBJECT_ID('AMBIGSUI') IS NOT NULL DROP TABLE AMBIGSUI
CREATE TABLE AMBIGSUI (
    SUI	NVARCHAR(10) NOT NULL,
    CUI	NCHAR(8) NOT NULL
);

IF OBJECT_ID('AMBIGLUI') IS NOT NULL DROP TABLE AMBIGLUI
CREATE TABLE AMBIGLUI (
    LUI	NVARCHAR(10) NOT NULL,
    CUI	NCHAR(8) NOT NULL
);

IF OBJECT_ID('MRDOC') IS NOT NULL DROP TABLE MRDOC
CREATE TABLE MRDOC (
    DOCKEY	NVARCHAR(50) NOT NULL,
    VALUE	NVARCHAR(200),
    TYPE	NVARCHAR(50) NOT NULL,
    EXPL	NVARCHAR(1000)
);

IF OBJECT_ID('MRSAB') IS NOT NULL DROP TABLE MRSAB
CREATE TABLE MRSAB (
    VCUI	NCHAR(8),
    RCUI	NCHAR(8),
    VSAB	NVARCHAR(40) NOT NULL,
    RSAB	NVARCHAR(40) NOT NULL,
    SON	NVARCHAR(3000) NOT NULL,
    SF	NVARCHAR(40) NOT NULL,
    SVER	NVARCHAR(40),
    VSTART	NCHAR(8),
    VEND	NCHAR(8),
    IMETA	NVARCHAR(10) NOT NULL,
    RMETA	NVARCHAR(10),
    SLC	NVARCHAR(1000),
    SCC	NVARCHAR(1000),
    SRL	INT NOT NULL,
    TFR	INT,
    CFR	INT,
    CXTY	NVARCHAR(50),
    TTYL	NVARCHAR(400),
    ATNL	NVARCHAR(4000),
    LAT	NCHAR(3),
    CENC	NVARCHAR(40) NOT NULL,
    CURVER	NCHAR(1) NOT NULL,
    SABIN	NCHAR(1) NOT NULL,
    SSN	NVARCHAR(3000) NOT NULL,
    SCIT	NVARCHAR(4000) NOT NULL
)

IF OBJECT_ID('MRCOLS') IS NOT NULL DROP TABLE MRCOLS
CREATE TABLE MRCOLS (
    COL	NVARCHAR(40),
    DES	NVARCHAR(200),
    REF	NVARCHAR(40),
    MIN	INT,
    AV	NUMERIC(5,2),
    MAX	INT,
    FIL	NVARCHAR(50),
    DTY	NVARCHAR(40)
)

IF OBJECT_ID('MRRANK') IS NOT NULL DROP TABLE MRRANK
CREATE TABLE MRRANK (
    RANK	INT NOT NULL,
    SAB	    NVARCHAR(40) NOT NULL,
    TTY	    NVARCHAR(40) NOT NULL,
    SUPPRESS	NCHAR(1) NOT NULL
)

IF OBJECT_ID('MRFILES') IS NOT NULL DROP TABLE MRFILES
CREATE TABLE MRFILES (
    FIL	NVARCHAR(50) NULL,
    DES	NVARCHAR(200) NULL,
    FMT	NVARCHAR(300) NULL,
    CLS	INT NULL,
    RWS	INT NULL,
    BTS	INT NULL
)